name: IAMTYRRELL
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25034
title: '#IAMTYRRELL'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#05227e'
    - '#3598db'
    - '#89d8f9'
    - '#cfe0f0'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
